### ISSUE TITLE
Mismatch in name between defaults package

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/backports.functools_lru_cache-feedstock#10]
Just wanted to note a mismatch in names between this package, `backports.functools_lru_cache-feedstock` and the same package in the defaults channel which is named `functools_lru_cache`. If we could find a way to agree upon a preferred name that would be helpful to everyone involved.

**Comment by stuertz** [comment]
Hm, bad. AFAIR we had this package here before the defaults channel did.
Presumably we should adopt the default name.
I think it is not a good idea to rename, but to drop support on this package and setup a new package with the default name.

@conda-forge-manager  What is the default way to proceed in this case?

**Comment by ocefpaf** [comment]
@stuertz this issue happens in other feedstocks too and we are not yet certain of the best solution.
I am inclined to say that namedspaced packages and the original name should be preserved. That means `defaults` should rename their package :stuck_out_tongue_winking_eye:

However, we will need to discuss this further to find a solution that fits both channels and reduces the incompatibilities.  If it comes to abandoning the namedspaced package/original name your suggestion is :+1:

**Comment by ocefpaf** [comment]
@jjhelmus what is the status on this? Should we close it?

**Comment by jjhelmus** [comment]
`backports.functools_lru_cache` is available in `defaults` and is the preferred.  A `functools_lru_cache` meta-package which points to the backports package is also included to provide the requirement for any existing packages which use this name.  

Closing.
